import { z } from "zod";
import type { PlanPromptVersion } from "./studio-plan-prompt-versions";
import { inspectQualityLedgers } from "../../scripts/local-data-quality-ledgers.mjs";
import {
  providerDigest as digest,
  providerStartSchema,
  providerStartDigestInput,
  createProviderBudgetEvent,
  createProviderRun,
  createProviderArtifact,
  createProviderReceipt,
} from "../../scripts/local-data-quality-provider.mjs";
import {
  createProviderPreparation,
  createVersionedProviderPreparationBuilder,
  validateNewProviderPreparation,
} from "./studio-plan-quality-provider-core";
import {
  providerConfigurationProposalSchema,
  providerReviewInputSchema,
} from "./studio-plan-quality-provider-review-types";
import { providerReservationCommandSchema } from "./studio-plan-quality-provider-reservation-command";
import { providerReservationReviewSchema } from "./studio-plan-quality-provider-reservation-review-types";
import type { ProviderReservationBinding } from "./studio-plan-quality-provider-reservation-archive-types";
import { validateProviderReservationBinding } from "../../scripts/local-data-quality-provider-reservation-binding.mjs";
import {
  isProviderReservationReviewCurrent,
  isVersionedProviderReservationReviewCurrent,
  type ProviderReservationReviewInput,
} from "./studio-plan-quality-provider-reservation-review";
import type {
  ProviderStart,
  ProviderRun,
  ProviderBudgetEvent,
  ProviderReceipt,
  ProviderArtifact,
} from "./studio-plan-quality-provider-types";

const same = (a: unknown, b: unknown) => digest(a) === digest(b);
const bytes = (value: unknown) => Buffer.byteLength(JSON.stringify(value), "utf8");
export const providerReservationPlanLimits = {
  databaseBytes: 256 * 1024 * 1024,
  bindingBytes: 64 * 1024,
} as const;

/** Stable identity for retrying the original command, distinct from the frozen provider-start digest. */
export function providerReservationCommandDigest(value: unknown): string {
  return digest(providerReservationCommandSchema.parse(value));
}

export type ProviderReservationWritePlan = {
  planVersion: 1;
  status: "prepared-not-committed";
  transaction: "single-immediate-transaction-required";
  persistence: "audited-v8-transaction-required";
  start: ProviderStart;
  rows: {
    run: ProviderRun;
    artifact: ProviderArtifact;
    budgetEvent: ProviderBudgetEvent;
    receipt: ProviderReceipt;
    binding: ProviderReservationBinding;
  };
  capacity: {
    additionalUsedBytes: number;
    bindingBytes: number;
    totalExposureBytes: number;
    reservedBudgetEventSlots: number;
    reservedReceiptSlots: number;
  };
  dispatchAllowed: false;
};
type Refusal =
  | "invalid-input"
  | "scope-changed"
  | "ledger-invalid"
  | "nonce-conflict"
  | "run-id-conflict"
  | "review-not-current"
  | "reservation-blocked"
  | "bindings-changed"
  | "approval-time-invalid"
  | "preparation-invalid"
  | "capacity-exceeded"
  | "planned-ledger-invalid"
  | "native-version-unsupported";
export type ProviderReservationPlanResult =
  | { status: "prepared"; plan: ProviderReservationWritePlan }
  | { status: "refused"; reason: Refusal; plan: null };
const refuse = (reason: Refusal): ProviderReservationPlanResult => ({
  status: "refused",
  reason,
  plan: null,
});
export type ProviderReservationPlannerInput = {
  command: unknown;
  review: unknown;
  /** Fresh, server-owned snapshot under the writer's lock; never a browser-supplied ledger. */
  current: ProviderReservationReviewInput;
  /** Generated by the server for a NEW operation only. Existing nonces must use audited replay. */
  runId: string;
  /** Validated DB bytes outside inspectQualityLedgers' accounting, including existing bindings
   * and raw-row encoding overhead. Required even when zero; never inferred from client input. */
  additionalUsedBytes: number;
};

/** No IO or grants. This is not a persistence API: its writer must atomically audit/store the
 * binding AND the frozen native rows, with migration/backup coverage and exact-command replay. */
export function prepareProviderReservation(
  input: ProviderReservationPlannerInput,
): ProviderReservationPlanResult {
  return prepareReservation(input, null);
}

/** Recheck the selected approval under the writer lock. A v2 selection must not downgrade
 * into frozen v1 native rows while the separate v2 archive/runtime is being connected. */
export function prepareVersionedProviderReservation(
  version: PlanPromptVersion,
  input: ProviderReservationPlannerInput,
): ProviderReservationPlanResult {
  createVersionedProviderPreparationBuilder(version);
  return prepareReservation(input, version);
}
function prepareReservation(
  input: ProviderReservationPlannerInput,
  version: PlanPromptVersion | null,
): ProviderReservationPlanResult {
  const commandInput = providerReservationCommandSchema.safeParse(input.command);
  const reviewInput = providerReservationReviewSchema.safeParse(input.review);
  const selection = providerReviewInputSchema.safeParse(input.current.selection);
  if (
    !commandInput.success ||
    !reviewInput.success ||
    !selection.success ||
    !z.string().uuid().safeParse(input.runId).success ||
    !z.string().datetime().safeParse(input.current.inspectedAt).success ||
    !Number.isSafeInteger(input.additionalUsedBytes) ||
    input.additionalUsedBytes < 0
  )
    return refuse("invalid-input");
  const command = commandInput.data,
    review = reviewInput.data,
    p = review.policyReview;
  const scope = {
    version: command.version,
    versionDigest: command.versionDigest,
    candidateId: command.candidateId,
  };
  if (
    !same(scope, selection.data) ||
    scope.version !== p.scope.version ||
    scope.versionDigest !== p.scope.versionDigest ||
    scope.candidateId !== p.scope.candidateId
  )
    return refuse("scope-changed");

  let state: ReturnType<typeof inspectQualityLedgers>;
  try {
    state = inspectQualityLedgers(input.current.ledger);
  } catch {
    return refuse("ledger-invalid");
  }
  // A binding references this native receipt's nonce; it is not another operation/nonces owner.
  const usedNonces = [
    ...(input.current.ledger.otherNonces ?? []),
    ...state.legacy.receipts.map((row) => row.clientRequestId),
    ...state.provider.receipts.map((row) => row.clientRequestId),
    ...state.policy.records.map((row) => row.clientRequestId),
  ];
  if (usedNonces.includes(command.clientRequestId)) return refuse("nonce-conflict");
  if ([...state.legacy.runs, ...state.provider.runs].some((row) => row.id === input.runId))
    return refuse("run-id-conflict");
  if (
    command.approvedReviewDigest !== review.reviewDigest ||
    !(version === null
      ? isProviderReservationReviewCurrent(review, input.current)
      : isVersionedProviderReservationReviewCurrent(version, review, input.current))
  )
    return refuse("review-not-current");
  if (review.assessment.state !== "conditions-met") return refuse("reservation-blocked");
  if (
    !same(command.expectedPolicyHead, review.policyHead) ||
    !same(command.expectedPolicyReference, review.policy.reference) ||
    command.expectedLedgerDigest !== review.ledgerDigest ||
    !same(command.expectedBudgetHead, {
      revision: p.budget.revision,
      headDigest: p.budget.headDigest,
    }) ||
    command.expectedGlobalRunCount !== review.runs.globalCount ||
    command.expectedProductionRunCount !== review.runs.productionCount
  )
    return refuse("bindings-changed");
  const now = Date.parse(input.current.inspectedAt),
    approvedAt = Date.parse(command.approval.approvedAt);
  if (
    approvedAt < Date.parse(p.inspectedAt) ||
    approvedAt > now ||
    approvedAt >= Date.parse(p.expiresAt)
  )
    return refuse("approval-time-invalid");

  // Refuse before creating a v1 preparation, native rows, budget reservation or transport.
  if (version === "plan-observation-v2") return refuse("native-version-unsupported");

  const configuration = providerConfigurationProposalSchema.safeParse(input.current.configuration);
  const registry = input.current.ledger.registries.find((row) => row.version === command.version);
  if (!configuration.success || !registry) return refuse("preparation-invalid");
  let start: ProviderStart;
  try {
    const config = configuration.data,
      budget = p.budget;
    const preparation = createProviderPreparation({
      registry,
      candidateId: command.candidateId,
      environment: "production",
      preparedAt: p.inspectedAt,
      expiresAt: p.expiresAt,
      financialInput: {
        evidenceMode: "official-reviewed",
        model: config.model,
        calculatedAt: p.inspectedAt,
        outputReservationTokens: config.outputReservationTokens,
        conditions: config.conditions,
        context: config.context,
        pricing: config.pricing,
      },
      budget: {
        scopeId: budget.scopeId,
        revision: budget.revision,
        headDigest: budget.headDigest!,
        currency: budget.currency!,
        unitScale: budget.unitScale!,
        capUnits: budget.capUnits,
        heldUnits: budget.heldUnits,
        recognizedUnits: budget.recognizedUnits,
      },
      retention: config.retention,
    });
    validateNewProviderPreparation(preparation, registry, input.current.inspectedAt);
    const { scope, model, contract, generation, reviewTemplate } = preparation;
    if (
      digest({ scope, model, contract, generation, reviewTemplate }) !==
        p.bindings.requestReviewDigest ||
      digest(preparation.financialBasis) !== p.bindings.financialBasisDigest ||
      digest(preparation.retention) !== p.bindings.retentionDigest
    )
      return refuse("preparation-invalid");
    start = providerStartSchema.parse({
      clientRequestId: command.clientRequestId,
      expectedBudgetRevision: command.expectedBudgetHead.revision,
      expectedBudgetDigest: command.expectedBudgetHead.headDigest,
      expectedGlobalRunCount: command.expectedGlobalRunCount,
      expectedScopeRunCount: command.expectedProductionRunCount,
      preparation,
      approval: {
        provenance: "explicit-user",
        approvedPreparationDigest: preparation.preparationDigest,
        approvedAt: command.approval.approvedAt,
        expiresAt: p.expiresAt,
        acknowledgedReservationOnly: true,
        acknowledgedFinancialBasisNotTokenFit: true,
        acknowledgedRetention: true,
        acknowledgedNoAutomaticRetry: true,
      },
    });
  } catch {
    return refuse("preparation-invalid");
  }

  // Native reservation owns 16 budget and 64 receipt slots, including the initial rows.
  if (
    input.current.ledger.budgetEvents.length + state.reservedBudgetEventSlots + 16 > 1000 ||
    input.current.ledger.receipts.length + state.reservedReceiptSlots + 64 > 1000
  )
    return refuse("capacity-exceeded");
  try {
    const recordedAt = new Date(input.current.inspectedAt).toISOString();
    const startInputDigest = digest(providerStartDigestInput(start));
    const budgetEvent = createProviderBudgetEvent({
      schemaVersion: 2,
      scopeId: "candidate-quality-provider-v2-live",
      environment: "production",
      provenance: "explicit-user",
      revision: p.budget.revision + 1,
      previousDigest: p.budget.headDigest,
      eventId: command.clientRequestId,
      recordedAt,
      currency: p.budget.currency!,
      unitScale: p.budget.unitScale!,
      payload: {
        kind: "reserve-run",
        runId: input.runId,
        preparationDigest: start.preparation.preparationDigest,
        generationUnits: p.reservation.generationUnits,
        reviewUnits: p.reservation.reviewUnits,
      },
    });
    const run = createProviderRun({
      input: start,
      id: input.runId,
      recordedAt,
      reservation: budgetEvent,
    });
    const artifact = createProviderArtifact({
      runId: input.runId,
      body: JSON.stringify(start.preparation.generation.body),
    });
    const receipt = createProviderReceipt({
      schemaVersion: 2,
      scopeId: budgetEvent.scopeId,
      kind: "provider-start",
      clientRequestId: command.clientRequestId,
      inputDigest: startInputDigest,
      runId: input.runId,
      runRevision: 0,
      budgetRevision: budgetEvent.revision,
      operationDigest: run.runDigest,
      recordedAt,
    });
    const body: Omit<ProviderReservationBinding, "recordDigest"> = {
      recordVersion: 1,
      kind: "provider-reservation-policy-binding",
      clientRequestId: command.clientRequestId,
      command,
      commandDigest: providerReservationCommandDigest(command),
      approvedReview: review,
      runId: run.id,
      runDigest: run.runDigest,
      startInputDigest,
      recordedAt,
      dispatchAllowed: false,
    };
    const binding = { ...body, recordDigest: digest(body) };
    if (
      bytes(binding) > providerReservationPlanLimits.bindingBytes ||
      bytes(run) > 2 * 1024 * 1024 ||
      bytes(budgetEvent) > 32 * 1024 ||
      bytes(receipt) > 4096
    )
      return refuse("capacity-exceeded");
    // An untouched native run reserves its entire 32MiB, including these initial rows.
    // Check before the combined inspector so quota exhaustion is not reported as corruption.
    if (
      state.usedBytes +
        state.reservedBytes +
        run.storageReservationBytes +
        bytes(binding) +
        input.additionalUsedBytes >
      providerReservationPlanLimits.databaseBytes
    )
      return refuse("capacity-exceeded");
    const nextLedger = {
      ...input.current.ledger,
      runs: [...input.current.ledger.runs, run],
      artifacts: [...input.current.ledger.artifacts, artifact],
      budgetEvents: [...input.current.ledger.budgetEvents, budgetEvent],
      receipts: [...input.current.ledger.receipts, receipt],
    };
    const next = inspectQualityLedgers(nextLedger);
    validateProviderReservationBinding(binding, nextLedger);
    const totalExposureBytes =
      next.usedBytes + next.reservedBytes + bytes(binding) + input.additionalUsedBytes;
    if (totalExposureBytes > providerReservationPlanLimits.databaseBytes)
      return refuse("capacity-exceeded");
    return {
      status: "prepared",
      plan: {
        planVersion: 1,
        status: "prepared-not-committed",
        transaction: "single-immediate-transaction-required",
        persistence: "audited-v8-transaction-required",
        start,
        rows: { run, artifact, budgetEvent, receipt, binding },
        capacity: {
          additionalUsedBytes: input.additionalUsedBytes,
          bindingBytes: bytes(binding),
          totalExposureBytes,
          reservedBudgetEventSlots: next.reservedBudgetEventSlots,
          reservedReceiptSlots: next.reservedReceiptSlots,
        },
        dispatchAllowed: false,
      },
    };
  } catch {
    return refuse("planned-ledger-invalid");
  }
}
